/** Declaration file generated by dts-gen */

export = winston_elasticsearch;

declare class winston_elasticsearch {
    constructor(options: any);

    getIndexName(options: any): any;

    log(level: any, message: any, meta: any, callback: any): void;

    search(q: any): any;

}

declare namespace winston_elasticsearch {
    namespace prototype {
        const name: string;

        function addListener(type: any, listener: any): any;

        function emit(type: any, args: any): any;

        function eventNames(): any;

        function formatQuery(query: any): any;

        function formatResults(results: any, options: any): any;

        function getIndexName(options: any): any;

        function getMaxListeners(): any;

        function listenerCount(type: any): any;

        function listeners(type: any): any;

        function log(level: any, message: any, meta: any, callback: any): void;

        function logException(msg: any, meta: any, callback: any): any;

        function normalizeQuery(options: any): any;

        function on(type: any, listener: any): any;

        function once(type: any, listener: any): any;

        function prependListener(type: any, listener: any): any;

        function prependOnceListener(type: any, listener: any): any;

        function rawListeners(type: any): any;

        function removeAllListeners(type: any, ...args: any[]): any;

        function removeListener(type: any, listener: any): any;

        function search(q: any): any;

        function setMaxListeners(n: any): any;

        namespace addListener {
            const prototype: {
            };

        }

        namespace emit {
            const prototype: {
            };

        }

        namespace eventNames {
            const prototype: {
            };

        }

        namespace formatQuery {
            const prototype: {
            };

        }

        namespace formatResults {
            const prototype: {
            };

        }

        namespace getIndexName {
            const prototype: {
            };

        }

        namespace getMaxListeners {
            const prototype: {
            };

        }

        namespace listenerCount {
            const prototype: {
            };

        }

        namespace listeners {
            const prototype: {
            };

        }

        namespace log {
            const prototype: {
            };

        }

        namespace logException {
            const prototype: {
            };

        }

        namespace normalizeQuery {
            const prototype: {
            };

        }

        namespace on {
            const prototype: {
            };

        }

        namespace once {
            const prototype: {
            };

        }

        namespace prependListener {
            const prototype: {
            };

        }

        namespace prependOnceListener {
            const prototype: {
            };

        }

        namespace rawListeners {
            const prototype: {
            };

        }

        namespace removeAllListeners {
            const prototype: {
            };

        }

        namespace removeListener {
            const prototype: {
            };

        }

        namespace search {
            const prototype: {
            };

        }

        namespace setMaxListeners {
            const prototype: {
            };

        }

    }

}

